"""Add idProof column

Revision ID: 96e81bf556c5
Revises: 9c04b2e0a565
Create Date: 2025-01-03 14:45:14.370818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e81bf556c5'
down_revision = '9c04b2e0a565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProof', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('qualification', sa.String(length=255), nullable=False))
        batch_op.alter_column('service_type',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('certifications',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('certification_path')
        batch_op.drop_column('id_proof_path')
        batch_op.drop_column('qualification_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('id_proof_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('certification_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.alter_column('certifications',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('service_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('qualification')
        batch_op.drop_column('idProof')

    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
