"""Add service provider columns to User model

Revision ID: 9c04b2e0a565
Revises: 
Create Date: 2025-01-02 09:45:15.091862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c04b2e0a565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_proof_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('qualification_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('certification_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('certification_path')
        batch_op.drop_column('qualification_path')
        batch_op.drop_column('id_proof_path')
        batch_op.drop_column('experience')
        batch_op.drop_column('certifications')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('location')
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
